# Generated by Django 3.0.1 on 2019-12-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20191226_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='no_of_tasks',
        ),
    ]
