# Generated by Django 3.0.1 on 2020-01-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_list_no_of_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='list_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='name',
        ),
    ]
